name: Generate GitHub App user access token and refresh token by exchanging auth code

on:
  issues:
    types:
      - opened

jobs:
  gen_user_auth_tokens:
    if: startsWith(github.event.issue.title, '[gen-user-auth-tokens-github]')
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name == 'main' && 'production' || github.ref_name }}
      deployment: false
    env:
      AUTH_CLIENT_ID: ${{ vars.AUTH_CLIENT_ID }}
      AUTH_CLIENT_SECRET: ${{ secrets.AUTH_CLIENT_SECRET }}
      CLASSROOM_RSA_PRIVATE_KEY: ${{ secrets.CLASSROOM_RSA_PRIVATE_KEY }}
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: 'repo'
      
      - name: Install workflow util dependencies
        working-directory: 'repo/workflow-util'
        run: |
          npm i
      
      - name: Generate user auth tokens
        run: |
          # Use node script to decode issue body and decrypt via
          # CLASSROOM_RSA_PRIVATE_KEY
          workflow_inputs_json=$(node repo/workflow-util/decodeissuebody.js --data="${{ github.event.issue.body }}")

          AUTH_CODE=$(echo "$workflow_inputs_json" | jq -r '.authCode')
          PKCE_CODE_VERIFIER=$(echo "$workflow_inputs_json" | jq -r '.pkceCodeVerifier')
          export RESULT_ENCRYPTION_KEY=$(echo "$workflow_inputs_json" | jq -r '.resultEncryptionKey')
          VERIFIER=$(echo "$workflow_inputs_json" | jq -r '.verifier')
          
          # Generate issue comment
          issue_comment=$(node repo/workflow-util/genissuecomment.js --runId="$GITHUB_RUN_ID" --verifier="$VERIFIER")

          # Post issue comment so that client has run ID and can poll
          # workflow for status + artifacts
          post_comment_status=$(curl -s -o curl.json -w "%{http_code}" -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments" \
            -d '{"body":"'"$issue_comment"'"}')

          if [[ "$post_comment_status" != "201" ]]
          then
              echo "Error: Got HTTP status $post_comment_status when posting issue comment" >&2
              exit 1
          fi

          # Convert result encryption key from base64url to regular base64
          export RESULT_ENCRYPTION_KEY=$(echo -n "$RESULT_ENCRYPTION_KEY" | tr '_-' '/+')

          # Prepare result directory
          mkdir -p result
          rm -rf result/*

          function secureresults() {
              # Zip results for encryption
              zip -qr result.zip result/*
              rm -f result/*

              # Encrypt result.zip. Generates result.zip.enc, aes-key.enc, and
              # iv.bin in result/
              node repo/workflow-util/secureresults.js --file=result.zip
              
              # Delete plaintext result.zip
              rm -f result.zip
          }

          # TODO defaults for env vars, and error-handle for missing
          # required vars / secrets
          
          # Mask auth code and code verifier in logs
          echo "::add-mask::$AUTH_CODE"
          echo "::add-mask::$PKCE_CODE_VERIFIER"

          # Retrieve auth tokens via cURL request
          auth_status=$(curl -X POST -s -o curl.json -w "%{http_code}" -H "Accept: application/vnd.github+json" "https://github.com/login/oauth/access_token" \
            --url-query "client_id=$AUTH_CLIENT_ID" \
            --url-query "client_secret=$AUTH_CLIENT_SECRET" \
            --url-query "code=$AUTH_CODE" \
            --url-query "code_verifier=$PKCE_CODE_VERIFIER")
          
          if [[ "$auth_status" != 200 ]]
          then
              echo -n '{"status": "failure"}' > result/status.json
              secureresults
              exit 0
          fi

          access_token=$(cat curl.json | jq '.access_token')
          refresh_token=$(cat curl.json | jq '.refresh_token')
          access_token_expires_in=$(cat curl.json | jq '.expires_in')
          refresh_token_expires_in=$(cat curl.json | jq '.refresh_token_expires_in')

          rm -f curl.json

          # Mask tokens in logs
          echo "::add-mask::$access_token"
          echo "::add-mask::$refresh_token"

          # Store result
          echo -n '{"accessToken": '"$access_token"', "refreshToken": '"$refresh_token"', "accessTokenExpiresInSeconds": '"$access_token_expires_in"', "refreshTokenExpiresInSeconds": '"$refresh_token_expires_in"'}' > result/data.json
          echo -n '{"status": "success"}' > result/status.json
          secureresults
          exit 0

      - name: Upload secure results
        uses: actions/upload-artifact@v4
        with:
          name: result
          path: result/
          retention-days: 1
