- name: assignment-1
  key: ASSIGNMENT_1_KEY
- name: assignment-2 # This creates assignment-2 even though there's no template directory for it. When accepted, the student's generated repository will be empty with no commits.
  key: ASSIGNMENT_2_KEY
- name: assignment-3 # Notice: No accept key. If the accept key is omitted (or the assignment has a template directory but no entry in assignments.conf), then no accept key is necessary to accept the assignment.
