name: Accept Assignment

on:
  workflow_dispatch:
    inputs:
      userAuthToken:
        description: "OAuth token for student's GitHub / GitLab account"
        required: true
      assignmentAcceptKey:
        description: "Key that references the assignment to be accepted"

env:
  ASSIGNMENT_READ_USERNAME: ${{ vars.ASSIGNMENT_READ_USERNAME }}
  ASSIGNMENT_READ_TOKEN: ${{ secrets.ASSIGNMENT_READ_TOKEN }}
  ASSIGNMENT_REPO: ${{ vars.ASSIGNMENT_REPO || github.repository }}
  ASSIGNMENT_ACCEPT_KEY: ${{ inputs.assignmentAcceptKey }}
  USER_AUTH_TOKEN: ${{ inputs.userAuthToken }}

jobs:
  accept-assignment:
    runs-on: ubuntu-latest
    steps:
      # Clone the assignment repository
      - name: Checkout Code
        run: |
          # Mask user oauth token in logs
          echo "::add-mask::$USER_OAUTH_TOKEN"
          
          # Clone assignment repo
          git clone "https://${ASSIGNMENT_READ_USERNAME}:${ASSIGNMENT_READ_TOKEN}@${ASSIGNMENT_REPO}" assignments-repo

          # List repo files TODO remove
          ls assignments-repo

          # TODO Figure out which assignment they're trying to accept by decrypting
          # assignment accept key to get assignment directory name, using
          # AES key GH secret

          # Get user's GitHub username
          # TODO
