name: Use user refresh token to generate new user access token and refresh token for GitHub App

on:
  workflow_dispatch:
    inputs:
      userRefreshToken:
        description: "Refresh token for GitHub App user"
        required: true
      resultEncryptionKey:
        description: "Public encryption key that should be used to encrypt the results."
        required: true
  
env:
  USER_REFRESH_TOKEN: ${{ inputs.userRefreshToken }}
  RESULT_ENCRYPTION_KEY: ${{ inputs.resultEncryptionKey }}

jobs:
  gen_user_auth_tokens:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name == 'main' && 'production' || github.ref_name }}
      deployment: false
    env:
      AUTH_APP_ID: ${{ vars.AUTH_APP_ID }}
      AUTH_APP_SECRET: ${{ secrets.AUTH_APP_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: 'repo'

      - name: Install workflow util dependencies
        working-directory: 'repo/workflow-util'
        run: |
          npm i

      - name: Generate user auth tokens
        run: |
          # Convert result encryption key from base64url to regular base64
          export RESULT_ENCRYPTION_KEY=$(echo -n "$RESULT_ENCRYPTION_KEY" | tr '_-' '/+')

          # Prepare result directory
          mkdir -p result
          rm -rf result/*

          function secureresults() {
              # Zip results for encryption
              zip -qr result.zip result/*
              rm -f result/*

              # Encrypt result.zip. Generates result.zip.enc, aes-key.enc, and
              # iv.bin in result/
              node repo/workflow-util/secureresults.js -f result.zip
              
              # Delete plaintext result.zip
              rm -f result.zip
          }

          # TODO defaults for env vars, and error-handle for missing
          # required vars / secrets
          
          # Mask refresh token in logs
          echo "::add-mask::$USER_REFRESH_TOKEN"

          # Retrieve auth tokens via cURL request
          auth_status=$(curl -X POST -s -o curl.json -w "%{http_code}" -H "Accept: application/vnd.github+json" "https://github.com/login/oauth/access_token" \
            --url-query "client_id=${AUTH_APP_ID}" \
            --url-query "client_secret=${AUTH_APP_SECRET}" \
            --url-query "grant_type=refresh_token" \
            --url-query "refresh_token=${USER_REFRESH_TOKEN}")

          if [[ "$auth_status" != 200 ]]
          then
              echo -n '{"status": "failure"}' > result/status.json
              secureresults
              exit 0
          fi

          access_token=$(cat curl.json | jq '.access_token')
          refresh_token=$(cat curl.json | jq '.refresh_token')
          access_token_expires_in=$(cat curl.json | jq '.expires_in')
          refresh_token_expires_in=$(cat curl.json | jq '.refresh_token_expires_in')

          rm -f curl.json

          # Mask tokens in logs
          echo "::add-mask::$access_token"
          echo "::add-mask::$refresh_token"

          # Store result
          echo -n '{"accessToken": '"$access_token"', "refreshToken": '"$refresh_token"', "accessTokenExpiresInSeconds": '"$access_token_expires_in"', "refreshTokenExpiresInSeconds": '"$refresh_token_expires_in"'}' > result/data.json
          echo -n '{"status": "success"}' > result/status.json
          secureresults
          exit 0

      - name: Upload secure results
        uses: actions/upload-artifact@v4
        with:
          name: result
          path: result/
          retention-days: 1
